{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/nandiniorugunta/streamlit/blob/main/code1.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "-Gz_eZpaNz5J",
        "outputId": "77b5fa82-1f5b-435c-8a25-6671be00b66a"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Collecting streamlit\n",
            "  Downloading streamlit-1.32.2-py2.py3-none-any.whl (8.1 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m8.1/8.1 MB\u001b[0m \u001b[31m58.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.2.2)\n",
            "Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit) (1.4)\n",
            "Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.3.3)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.1.7)\n",
            "Requirement already satisfied: numpy<2,>=1.19.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.25.2)\n",
            "Collecting packaging<24,>=16.8 (from streamlit)\n",
            "  Downloading packaging-23.2-py3-none-any.whl (53 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m53.0/53.0 kB\u001b[0m \u001b[31m7.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: pandas<3,>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.5.3)\n",
            "Requirement already satisfied: pillow<11,>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.4.0)\n",
            "Requirement already satisfied: protobuf<5,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.20.3)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (14.0.2)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.31.0)\n",
            "Requirement already satisfied: rich<14,>=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (13.7.1)\n",
            "Requirement already satisfied: tenacity<9,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.2.3)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.10.0)\n",
            "Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)\n",
            "  Downloading GitPython-3.1.42-py3-none-any.whl (195 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m195.4/195.4 kB\u001b[0m \u001b[31m23.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.8.1b0-py2.py3-none-any.whl (4.8 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m4.8/4.8 MB\u001b[0m \u001b[31m88.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.3.3)\n",
            "Collecting watchdog>=2.1.5 (from streamlit)\n",
            "  Downloading watchdog-4.0.0-py3-none-manylinux2014_x86_64.whl (82 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m83.0/83.0 kB\u001b[0m \u001b[31m10.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.4)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (3.1.3)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (4.19.2)\n",
            "Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.12.1)\n",
            "Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
            "  Downloading gitdb-4.0.11-py3-none-any.whl (62 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m62.7/62.7 kB\u001b[0m \u001b[31m8.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2023.4)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.6)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2.0.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2024.2.2)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (2.16.1)\n",
            "Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
            "  Downloading smmap-5.0.1-py3-none-any.whl (24 kB)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.5)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.2.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.12.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.34.0)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.18.0)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas<3,>=1.3.0->streamlit) (1.16.0)\n",
            "Installing collected packages: watchdog, smmap, packaging, pydeck, gitdb, gitpython, streamlit\n",
            "  Attempting uninstall: packaging\n",
            "    Found existing installation: packaging 24.0\n",
            "    Uninstalling packaging-24.0:\n",
            "      Successfully uninstalled packaging-24.0\n",
            "Successfully installed gitdb-4.0.11 gitpython-3.1.42 packaging-23.2 pydeck-0.8.1b0 smmap-5.0.1 streamlit-1.32.2 watchdog-4.0.0\n"
          ]
        }
      ],
      "source": [
        "!pip install streamlit"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "FCLdeT3C9GpG"
      },
      "source": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "uTGn4ySN9Gkp"
      },
      "source": []
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "lx6qWmEAdDmV",
        "outputId": "171b1b14-59b8-449b-90ff-e922c1655be8"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Overwriting python.py\n"
          ]
        }
      ],
      "source": [
        "%%writefile python.py\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "st.title(\"JNTUA COLLEGE OF ENGINEERING KALIKIRI\")\n",
        "import streamlit as st\n",
        "\n",
        "# Function to authenticate users\n",
        "def authenticate(username, password):\n",
        "    # Hardcoded username and password (replace with actual authentication logic)\n",
        "    VALID_USERNAME = \"jntuacek\"\n",
        "    VALID_PASSWORD = \"ece\"\n",
        "\n",
        "    if username == VALID_USERNAME and password == VALID_PASSWORD:\n",
        "        return True\n",
        "    else:\n",
        "        return False\n",
        "\n",
        "# Streamlit app\n",
        "def main():\n",
        "    # If user is not authenticated, show login form\n",
        "    if 'authenticated' not in st.session_state or not st.session_state.authenticated:\n",
        "        st.subheader('Login')\n",
        "        username = st.text_input('Username')\n",
        "        password = st.text_input('Password', type='password')\n",
        "        if st.button('Login'):\n",
        "            if authenticate(username, password):\n",
        "                st.session_state.authenticated = True\n",
        "                st.success('You have successfully logged in!')\n",
        "            else:\n",
        "                st.error('Invalid username or password. Please try again.')\n",
        "\n",
        "    # If user is authenticated, show the content\n",
        "    if 'authenticated' in st.session_state and st.session_state.authenticated:\n",
        "        st.subheader('Authenticated Content')\n",
        "        uploaded_file = st.file_uploader(\"Upload your file\")\n",
        "        if uploaded_file is not None:\n",
        "            file_contents = uploaded_file.read()\n",
        "            df=pd.read_excel(file_contents)\n",
        "            df = df.fillna(\"\")\n",
        "            st.dataframe(df)\n",
        "        df['Unnamed: 12'] = pd.to_numeric(df['Unnamed: 12'], errors='coerce')\n",
        "        df['Unnamed: 2'] = pd.to_numeric(df['Unnamed: 2'], errors='coerce')\n",
        "        df['Unnamed: 3'] = pd.to_numeric(df['Unnamed: 3'], errors='coerce')\n",
        "        df['Unnamed: 4'] = pd.to_numeric(df['Unnamed: 4'], errors='coerce')\n",
        "        df['Unnamed: 5'] = pd.to_numeric(df['Unnamed: 5'], errors='coerce')\n",
        "        df['Unnamed: 6'] = pd.to_numeric(df['Unnamed: 6'], errors='coerce')\n",
        "        df['Unnamed: 7'] = pd.to_numeric(df['Unnamed: 7'], errors='coerce')\n",
        "        df['Unnamed: 8'] = pd.to_numeric(df['Unnamed: 8'], errors='coerce')\n",
        "        df['Unnamed: 9'] = pd.to_numeric(df['Unnamed: 9'], errors='coerce')\n",
        "        df['Unnamed: 10'] = pd.to_numeric(df['Unnamed: 10'], errors='coerce')\n",
        "\n",
        "        st.sidebar.title(\"result analysis\")\n",
        "        if st.sidebar.button(\"1st class with Distinction(>70%)\"):\n",
        "            d=df.loc[df['Unnamed: 12']>=70]\n",
        "            st.sidebar.write(\"count:\",len(d))\n",
        "        if st.sidebar.button(\"1st class(60%-70%)\"):\n",
        "            e=df.loc[(df['Unnamed: 12']>=60)&(df['Unnamed: 12']<=70)]\n",
        "            st.sidebar.write(\"count:\",len(e))\n",
        "        if st.sidebar.button(\"2nd class(50%-60%)\"):\n",
        "            g=df.loc[(df['Unnamed: 12']>=50)&(df['Unnamed: 12']<=60)]\n",
        "            st.sidebar.write(\"count:\",len(g))\n",
        "        if st.sidebar.button(\"Failures(<40%)\"):\n",
        "            f=df.loc[df['Unnamed: 12']<=40]\n",
        "            st.sidebar.write(\"count:\",len(f))\n",
        "        st.sidebar.title(\"SUBJECT WISE PASS%:\")\n",
        "        if st.sidebar.button(\"EDC:\"):\n",
        "            value = df.iloc[69,2]\n",
        "            st.sidebar.write(value*100)\n",
        "        if st.sidebar.button(\"DE&VC:\"):\n",
        "            value = df.iloc[69,3]\n",
        "            st.sidebar.write(value*100)\n",
        "        if st.sidebar.button(\"CP&DS:\"):\n",
        "            value = df.iloc[69,4]\n",
        "            st.sidebar.write(value*100)\n",
        "        if st.sidebar.button(\"CHY:\"):\n",
        "            value = df.iloc[69,5]\n",
        "            st.sidebar.write(value*100)\n",
        "        if st.sidebar.button(\"IT WORKSHOP:\"):\n",
        "            value = df.iloc[69,6]\n",
        "            st.sidebar.write(value*100)\n",
        "        if st.sidebar.button(\"ENG WORKSHOP:\"):\n",
        "            value = df.iloc[69,7]\n",
        "            st.sidebar.write(value*100)\n",
        "        if st.sidebar.button(\"CHY LAB:\"):\n",
        "            value = df.iloc[69,8]\n",
        "            st.sidebar.write(value*100)\n",
        "        if st.sidebar.button(\"CP&DS LAB:\"):\n",
        "            value = df.iloc[69,9]\n",
        "            st.sidebar.write(value*100)\n",
        "        if st.sidebar.button(\"TOTAL PASS%\"):\n",
        "\n",
        "            st.sidebar.write(\"57.89\")\n",
        "\n",
        "        st.sidebar.title(\"SUB wise Fail Candidates:\")\n",
        "        if st.sidebar.button(\"EDC\"):\n",
        "            f=df.loc[df['Unnamed: 2']<25]\n",
        "            st.sidebar.write(\"count:\",len(f)-1)\n",
        "        if st.sidebar.button(\"DE&VC\"):\n",
        "            f=df.loc[df['Unnamed: 3']<25]\n",
        "            st.sidebar.write(\"count:\",len(f)-1)\n",
        "        if st.sidebar.button(\"CP&DS\"):\n",
        "            f=df.loc[df['Unnamed: 4']<25]\n",
        "            st.sidebar.write(\"count:\",len(f)-1)\n",
        "        if st.sidebar.button(\"CHY\"):\n",
        "            f=df.loc[df['Unnamed: 5']<25]\n",
        "            st.sidebar.write(\"count:\",len(f)-1)\n",
        "        if st.sidebar.button(\"IT WORKSHOP\"):\n",
        "            f=df.loc[df['Unnamed: 6']<25]\n",
        "            st.sidebar.write(\"count:\",len(f)-1)\n",
        "        if st.sidebar.button(\"ENGG WORKSHOP\"):\n",
        "            f=df.loc[df['Unnamed: 7']<25]\n",
        "            st.sidebar.write(\"count:\",len(f)-1)\n",
        "        if st.sidebar.button(\"EDC LAB\"):\n",
        "            f=df.loc[df['Unnamed: 8']<25]\n",
        "            st.sidebar.write(\"count:\",len(f)-1)\n",
        "        if st.sidebar.button(\"CP&DS LAB\"):\n",
        "            f=df.loc[df['Unnamed: 9']<25]\n",
        "            st.sidebar.write(\"count:\",len(f)-1)\n",
        "        if st.sidebar.button(\"CHY LAB\"):\n",
        "            f=df.loc[df['Unnamed: 10']<25]\n",
        "            st.sidebar.write(\"count:\",len(f)-1)\n",
        "\n",
        "\n",
        "if __name__ == '__main__':\n",
        "    main()\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "MFOCGIJeV8Xm"
      },
      "source": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "4lWRQjvlV8Eh"
      },
      "source": []
    },
    {
      "cell_type": "code",
      "source": [
        "!streamlit run python.py & npx localtunnel --port 8501"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "JaXsm0WfHVr-",
        "outputId": "d0f5d792-b96f-44e5-b96a-eefe9a24f746"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.\n",
            "\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[34m\u001b[1m  You can now view your Streamlit app in your browser.\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[34m  Network URL: \u001b[0m\u001b[1mhttp://172.28.0.12:8501\u001b[0m\n",
            "\u001b[34m  External URL: \u001b[0m\u001b[1mhttp://34.16.107.83:8501\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[K\u001b[?25hnpx: installed 22 in 5.168s\n",
            "your url is: https://late-wasps-beam.loca.lt\n",
            "2024-03-29 12:10:47.093 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/python.py\", line 124, in <module>\n",
            "    main()\n",
            "  File \"/content/python.py\", line 40, in main\n",
            "    df['Unnamed: 12'] = pd.to_numeric(df['Unnamed: 12'], errors='coerce')\n",
            "UnboundLocalError: local variable 'df' referenced before assignment\n",
            "2024-03-29 12:11:02.922 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:11:16.139 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:11:18.165 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:11:20.078 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:13:44.481 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/python.py\", line 124, in <module>\n",
            "    main()\n",
            "  File \"/content/python.py\", line 40, in main\n",
            "    df['Unnamed: 12'] = pd.to_numeric(df['Unnamed: 12'], errors='coerce')\n",
            "UnboundLocalError: local variable 'df' referenced before assignment\n",
            "2024-03-29 12:14:02.562 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:14:05.608 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/python.py\", line 124, in <module>\n",
            "    main()\n",
            "  File \"/content/python.py\", line 40, in main\n",
            "    df['Unnamed: 12'] = pd.to_numeric(df['Unnamed: 12'], errors='coerce')\n",
            "UnboundLocalError: local variable 'df' referenced before assignment\n",
            "2024-03-29 12:16:02.097 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:16:07.117 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:16:09.760 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:16:17.221 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:16:18.757 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:20:49.325 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/python.py\", line 124, in <module>\n",
            "    main()\n",
            "  File \"/content/python.py\", line 40, in main\n",
            "    df['Unnamed: 12'] = pd.to_numeric(df['Unnamed: 12'], errors='coerce')\n",
            "UnboundLocalError: local variable 'df' referenced before assignment\n",
            "2024-03-29 12:21:28.247 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/python.py\", line 124, in <module>\n",
            "    main()\n",
            "  File \"/content/python.py\", line 40, in main\n",
            "    df['Unnamed: 12'] = pd.to_numeric(df['Unnamed: 12'], errors='coerce')\n",
            "UnboundLocalError: local variable 'df' referenced before assignment\n",
            "2024-03-29 12:24:10.337 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/python.py\", line 124, in <module>\n",
            "    main()\n",
            "  File \"/content/python.py\", line 40, in main\n",
            "    df['Unnamed: 12'] = pd.to_numeric(df['Unnamed: 12'], errors='coerce')\n",
            "UnboundLocalError: local variable 'df' referenced before assignment\n",
            "2024-03-29 12:24:20.252 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:24:25.422 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:26:35.062 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:26:36.124 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:26:41.309 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:26:46.984 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:26:50.184 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:26:55.131 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:26:57.816 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:27:00.572 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:27:02.972 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:27:05.648 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:27:10.368 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:27:44.670 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/python.py\", line 124, in <module>\n",
            "    main()\n",
            "  File \"/content/python.py\", line 40, in main\n",
            "    df['Unnamed: 12'] = pd.to_numeric(df['Unnamed: 12'], errors='coerce')\n",
            "UnboundLocalError: local variable 'df' referenced before assignment\n",
            "2024-03-29 12:29:43.853 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:30:58.261 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/python.py\", line 124, in <module>\n",
            "    main()\n",
            "  File \"/content/python.py\", line 37, in main\n",
            "    df=pd.read_excel(file_contents)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 211, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 331, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/excel/_base.py\", line 482, in read_excel\n",
            "    io = ExcelFile(io, storage_options=storage_options, engine=engine)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/excel/_base.py\", line 1656, in __init__\n",
            "    raise ValueError(\n",
            "ValueError: Excel file format cannot be determined, you must specify an engine manually.\n",
            "2024-03-29 12:34:59.747 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/python.py\", line 124, in <module>\n",
            "    main()\n",
            "  File \"/content/python.py\", line 40, in main\n",
            "    df['Unnamed: 12'] = pd.to_numeric(df['Unnamed: 12'], errors='coerce')\n",
            "UnboundLocalError: local variable 'df' referenced before assignment\n",
            "2024-03-29 12:35:03.191 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/python.py\", line 124, in <module>\n",
            "    main()\n",
            "  File \"/content/python.py\", line 40, in main\n",
            "    df['Unnamed: 12'] = pd.to_numeric(df['Unnamed: 12'], errors='coerce')\n",
            "UnboundLocalError: local variable 'df' referenced before assignment\n",
            "2024-03-29 12:35:23.018 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-03-29 12:54:26.734 Session with id 7910a49a-0312-4dbc-8c74-37cd41e7a33f is already connected! Connecting to a new session.\n",
            "2024-03-29 12:58:27.653 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Expected bytes, got a 'int' object\", 'Conversion failed for column JNTUA COLLEGE OF  ENGINEERING: KALIKIRI  with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "I_9Bp1OyHdjo"
      },
      "execution_count": null,
      "outputs": []
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOK/tOEbDwIgVZ3bUi/yZNp",
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}